CAPI-32: Simplify fetch pubkey script

diff --git a/script/fetch-api-pubkey b/script/fetch-api-pubkey
--- a/script/fetch-api-pubkey
+++ b/script/fetch-api-pubkey
@@ -1,51 +1,36 @@
 #!/bin/sh
 
-set -e
+set -o pipefail
 
 KK_HOST=${KK_HOST:-keycloak}
 KK_PORT=${KK_PORT:-8080}
 KK_REALM=${KK_REALM:-external}
-MAX_FETCH_ATTEMPTS=${MAX_FETCH_ATTEMPTS:-5}
+TARGET=${TARGET:-var/secret}
 
-ATTEMPT=0
-RETRY_TIMEOUT=1
-EXIT_CODE="0"
-REALM_DATA=""
+CURL_OPTS=${CURL_OPTS:-}
+REALM_DATA=$(curl -s -m5 --fail ${CURL_OPTS} "http://${KK_HOST}:${KK_PORT}/auth/realms/${KK_REALM}")
+EXIT_CODE=$?
 
-while (( $ATTEMPT < $MAX_FETCH_ATTEMPTS ))
-  do
-    echo "Fetching keycloak public key..."
+[ "${EXIT_CODE}" -ne "0" ] && {
+    echo "$0: [ ERROR ] Keycloak realm data fetching failed"
+    exit ${EXIT_CODE}
+}
 
-    set +e
-    REALM_DATA=$(curl -s -m3 "http://${KK_HOST}:${KK_PORT}/auth/realms/${KK_REALM}")
-    EXIT_CODE=$?
-    set -e
-    if [ "$EXIT_CODE" -eq "0" ]
-    then
-      break
-    fi
+[ -z "${REALM_DATA}" ] && {
+    echo "$0: [ ERROR ] Keycloak realm data is empty"
+    exit -1
+}
 
-    echo "Failure! Retrying in $RETRY_TIMEOUT.." 1>&2
+echo "$0: [ INFO  ] Keycloak realm data fetched successfully"
+echo "$0: [ DEBUG ] ${REALM_DATA}"
+echo "$0: [ INFO  ] Writing public key to: ${TARGET} ..."
 
-    sleep $RETRY_TIMEOUT
-    ATTEMPT=$(( ATTEMPT + 1 ))
-  done
+echo "-----BEGIN PUBLIC KEY-----" > ${TARGET}
+echo "${REALM_DATA}" | \
+    grep -Po '"public_key":.*?[^\\]",' | \
+    sed -e 's/public_key//' -e 's/[":,]//g' | \
+    fold -w80 \
+    >> ${TARGET}
+echo "-----END PUBLIC KEY-----" >> ${TARGET}
 
-if [ "$EXIT_CODE" -eq "0" ]
-then
-    echo "Keycloak public key fetched"
-
-    TARGET=${TARGET:-var/secret}
-
-    echo "-----BEGIN PUBLIC KEY-----" >> ${TARGET}
-    echo "${REALM_DATA}" | \
-        grep -Po '"public_key":.*?[^\\]",' | \
-        sed -e 's/public_key//' -e 's/[":,]//g' | \
-        fold -w80 \
-        >> ${TARGET}
-    echo "-----END PUBLIC KEY-----" >> ${TARGET}
-else
-    echo "Keycloak fetching failed"
-    exit $EXIT_CODE
-fi
-
+echo "$0: [ INFO  ] Everything is ok"
