CAPI-32 Add the worst bash script you have ever seen to fetch the key… (#11)
* CAPI-32 Add the worst bash script you have ever seen to fetch the keycloak public key

* CAPI-32: Simplify fetch pubkey script

diff --git a/script/fetch-api-pubkey b/script/fetch-api-pubkey
--- a/script/fetch-api-pubkey
+++ b/script/fetch-api-pubkey
@@ -1,19 +1,36 @@
 #!/bin/sh
 
-set -e
+set -o pipefail
 
 KK_HOST=${KK_HOST:-keycloak}
 KK_PORT=${KK_PORT:-8080}
 KK_REALM=${KK_REALM:-external}
-
-REALM_DATA=$(curl -s -m3 "http://${KK_HOST}:${KK_PORT}/auth/realms/${KK_REALM}")
-
 TARGET=${TARGET:-var/secret}
 
-echo "-----BEGIN PUBLIC KEY-----" >> ${TARGET}
+CURL_OPTS=${CURL_OPTS:-}
+REALM_DATA=$(curl -s -m5 --fail ${CURL_OPTS} "http://${KK_HOST}:${KK_PORT}/auth/realms/${KK_REALM}")
+EXIT_CODE=$?
+
+[ "${EXIT_CODE}" -ne "0" ] && {
+    echo "$0: [ ERROR ] Keycloak realm data fetching failed"
+    exit ${EXIT_CODE}
+}
+
+[ -z "${REALM_DATA}" ] && {
+    echo "$0: [ ERROR ] Keycloak realm data is empty"
+    exit -1
+}
+
+echo "$0: [ INFO  ] Keycloak realm data fetched successfully"
+echo "$0: [ DEBUG ] ${REALM_DATA}"
+echo "$0: [ INFO  ] Writing public key to: ${TARGET} ..."
+
+echo "-----BEGIN PUBLIC KEY-----" > ${TARGET}
 echo "${REALM_DATA}" | \
     grep -Po '"public_key":.*?[^\\]",' | \
     sed -e 's/public_key//' -e 's/[":,]//g' | \
     fold -w80 \
     >> ${TARGET}
 echo "-----END PUBLIC KEY-----" >> ${TARGET}
+
+echo "$0: [ INFO  ] Everything is ok"
